gst_pipeline_node:
  ros__parameters:
    gst_plugins_required:
      - 'rosgstbridge'
      - 'videoconvert'
      - 'x264'
      - 'rtp'
      - 'rtpmanager'
    gst_plugin_ros_packages:
      - gst_bridge
    gst_plugin_ros_package_subdirs:
      gst_bridge: lib/gst_bridge/
    simple_bins:
      - video_stream
    video_stream:
      descr: 'rosimagesrc ros-topic=/rc_agent/video_source ! videoconvert ! tee name=t t. ! queue ! videoconvert ! videoscale method=1 ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc tune=zerolatency bitrate=800 speed-preset=ultrafast key-int-max=30 ! rtph264pay pt=96 config-interval=1 ! udpsink host=192.168.0.23 port=5600 sync=false async=false t. ! queue ! videoconvert'
rc_agent:
  ros__parameters:
    video_pipeline: 'udpsrc port=5600 caps="application/x-rtp,media=video,encoding-name=H264,payload=96,clock-rate=90000" ! rtpjitterbuffer ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! video/x-raw,format=BGR ! appsink drop=true max-buffers=1 sync=false'
